<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 .\map.glb -T --draco /draco/
-->

<script>
  import { T, useTask } from "@threlte/core";
  import { useGltf, useDraco, Outlines } from "@threlte/extras";

  let {
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/map-transformed.glb", { dracoLoader: useDraco() });

  let refcoin = $state();
  let time = 0; // Variable para acumular el tiempo

  useTask((delta) => {
    if (!refcoin) return;

    time += delta; // Acumula el tiempo transcurrido
    const floatingHeight = Math.sin(time * 2) * 0.3; // Calcula la altura basada en función senoidal
    refcoin.position.y = 4.92 + floatingHeight; // 4.92 es la posición Y original
  });
</script>

<T.PointLight
  color="yellow"
  distance={4}
  intensity={60}
  position={[-1.5, 3.5, 1.5]}
/>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Mesh_0009.geometry}
      material={gltf.materials["Material_0.001"]}
      position={[-1.68, 2.26, 0]}
      rotation={[0, 0.1, 0]}
      scale={1.58}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0010.geometry}
      material={gltf.materials["Material_0.001"]}
      position={[-199.69, 2.26, -171.21]}
      rotation={[0, 0.94, 0]}
      scale={1.58}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0011.geometry}
      material={gltf.materials["Material_0.001"]}
      position={[226.8, 2.26, 224.63]}
      rotation={[Math.PI, -0.97, Math.PI]}
      scale={1.58}
    />

    <T.Group
      position={[-1.66, 4.92, 0.08]}
      rotation={[0, 0.06, -Math.PI]}
      scale={0.5}
      bind:ref={refcoin}
    >
      <T.PointLight
        color="white"
        distance={1}
        intensity={60}
        position={[0, 0, 2]}
      />

      <T.Mesh
        geometry={gltf.nodes.electroneum_1.geometry}
        material={gltf.materials["Material.027"]}
      >
        <Outlines color="white" />
        <Outlines color="hotpink" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>

      <T.Mesh
        geometry={gltf.nodes.electroneum_2.geometry}
        material={gltf.materials["SVGMat.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.electroneum_3.geometry}
        material={gltf.materials["SVGMat.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.electroneum_4.geometry}
        material={gltf.materials["SVGMat.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.electroneum_5.geometry}
        material={gltf.materials["SVGMat.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.electroneum_6.geometry}
        material={gltf.materials["SVGMat.008"]}
      />
    </T.Group>

    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Suelo_1.geometry}
        material={gltf.materials["Material.005"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Suelo_2.geometry}
        material={gltf.materials["Material.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Suelo_3.geometry}
        material={gltf.materials["Material.026"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Suelo_1.geometry}
        material={gltf.materials["Material.005"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Suelo_2.geometry}
        material={gltf.materials["Material.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Suelo_3.geometry}
        material={gltf.materials["Material.026"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Puente.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Puente_1.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Puente.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Puente_1.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle003_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle003_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle003_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle003_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle004_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle004_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle004_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle004_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Escalera1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Escalera1_1.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Escalera1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Escalera1_1.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle005_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle005_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle005_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle005_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Escalera2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Escalera2_1.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Escalera2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Escalera2_1.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle006_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle006_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle006_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle006_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.canon1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.canon1_1.geometry}
        material={gltf.materials["Material.023"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.canon1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.canon1_1.geometry}
        material={gltf.materials["Material.023"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.canon2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.canon2_1.geometry}
        material={gltf.materials["Material.023"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.canon2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.canon2_1.geometry}
        material={gltf.materials["Material.023"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.canon3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.canon3_1.geometry}
        material={gltf.materials["Material.023"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.canon3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.canon3_1.geometry}
        material={gltf.materials["Material.023"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle002_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle002_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle002_1.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle002_2.geometry}
        material={gltf.materials["Material.009"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Casa2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_2.geometry}
        material={gltf.materials["Material.013"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_4.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_5.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_6.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Casa2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_2.geometry}
        material={gltf.materials["Material.013"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_4.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_5.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa2_6.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Casa1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_2.geometry}
        material={gltf.materials["Material.013"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_3.geometry}
        material={gltf.materials["Material.018"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_4.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_5.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_6.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Casa1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_2.geometry}
        material={gltf.materials["Material.013"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_3.geometry}
        material={gltf.materials["Material.018"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_4.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_5.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa1_6.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Casa4.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_4.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_5.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_6.geometry}
        material={gltf.materials["Material.013"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Casa4.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_4.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_5.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa4_6.geometry}
        material={gltf.materials["Material.013"]}
      />
    </T.Group>
    <T.Group position={[-198.57, 0, -172.46]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Casa3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_1.geometry}
        material={gltf.materials["Material.013"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_4.geometry}
        material={gltf.materials["Material.014"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_5.geometry}
        material={gltf.materials["Material.014"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_6.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_7.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Casa3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_1.geometry}
        material={gltf.materials["Material.013"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_2.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_3.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_4.geometry}
        material={gltf.materials["Material.014"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_5.geometry}
        material={gltf.materials["Material.014"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_6.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Casa3_7.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube032.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube007.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube006.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube033.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube009.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube008.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube034.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube011.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube010.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube035.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube012.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube014.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube037.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube018.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube038.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube015.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube022.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube039.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube016.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube053.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube050.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube040.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube046.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube017.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube025.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube066.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube041.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube019.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube068.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube042.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube021.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube071.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube044.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube023.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube089.geometry}
      material={gltf.materials["Material.007"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube045.geometry}
      material={gltf.materials["Material.007"]}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube024.geometry}
      material={gltf.materials["Material.007"]}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube051.geometry}
      material={gltf.materials["Material.007"]}
      position={[-150.21, -0.06, -0.3]}
      scale={6.79}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube054.geometry}
      material={gltf.materials["Material.007"]}
      position={[170.06, -0.06, 61.64]}
      scale={6.79}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube055.geometry}
      material={gltf.materials["Material.007"]}
      position={[-157.12, -0.06, 190.26]}
      scale={6.79}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube052.geometry}
      material={gltf.materials["Material.007"]}
      position={[77.07, -0.06, -102.35]}
      scale={6.79}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube056.geometry}
      material={gltf.materials["Material.007"]}
      position={[-3.06, 0.82, 1.43]}
      rotation={[0, -1.03, 0]}
      scale={1.67}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube047.geometry}
      material={gltf.materials["Material.007"]}
      position={[-200, 0.82, -168.73]}
      rotation={[0, -0.19, 0]}
      scale={1.67}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube026.geometry}
      material={gltf.materials["Material.007"]}
      position={[227.02, 0.82, 222.14]}
      rotation={[-Math.PI, 0.16, -Math.PI]}
      scale={1.67}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube057.geometry}
      material={gltf.materials["Material.007"]}
      position={[-0.27, 1.13, 1.85]}
      rotation={[0, 0.19, 0]}
      scale={1.15}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube049.geometry}
      material={gltf.materials["Material.007"]}
      position={[-197.37, 1.13, -171.02]}
      rotation={[0, 1.03, 0]}
      scale={1.15}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube059.geometry}
      material={gltf.materials["Material.007"]}
      position={[-201.24, 1.19, -172.58]}
      rotation={[0, 0.25, 0]}
      scale={1.32}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube027.geometry}
      material={gltf.materials["Material.007"]}
      position={[224.48, 1.13, 224.52]}
      rotation={[Math.PI, -1.06, Math.PI]}
      scale={1.15}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube064.geometry}
      material={gltf.materials["Material.007"]}
      position={[228.39, 1.19, 225.94]}
      rotation={[Math.PI, -0.29, Math.PI]}
      scale={1.32}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube058.geometry}
      material={gltf.materials["Material.007"]}
      position={[-1.69, 1.19, -2.07]}
      rotation={[0, -0.59, 0]}
      scale={1.32}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0.geometry}
      material={gltf.materials.Material_0}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0006.geometry}
      material={gltf.materials.Material_0}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0003.geometry}
      material={gltf.materials.Material_0}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0001.geometry}
      material={gltf.materials.Material_0}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0007.geometry}
      material={gltf.materials.Material_0}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0004.geometry}
      material={gltf.materials.Material_0}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0002.geometry}
      material={gltf.materials.Material_0}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0008.geometry}
      material={gltf.materials.Material_0}
      position={[-198.57, 0, -172.46]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0005.geometry}
      material={gltf.materials.Material_0}
      position={[225.72, 0, 225.92]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials["Material.004"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials["Material.004"]}
      position={[-64.88, -0.58, -143.15]}
      rotation={[-Math.PI, 0.8, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane004.geometry}
      material={gltf.materials["Material.004"]}
      position={[-4.18, -0.58, 177.02]}
      rotation={[Math.PI, -0.58, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane012.geometry}
      material={gltf.materials["Material.004"]}
      position={[-248.51, -0.58, -0.21]}
      rotation={[Math.PI, -0.58, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane013.geometry}
      material={gltf.materials["Material.004"]}
      position={[221.19, -0.58, 139.09]}
      rotation={[Math.PI, -0.58, Math.PI]}
    />
    <T.Group
      position={[-65.2, 12.4, -142.35]}
      rotation={[-Math.PI, 0.8, -Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle008_1.geometry}
        material={gltf.materials["Material.005"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_2.geometry}
        material={gltf.materials.azul}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_3.geometry}
        material={gltf.materials["Material.002"]}
      />
    </T.Group>
    <T.Group
      position={[-3.45, 12.4, 177.48]}
      rotation={[Math.PI, -0.58, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle008_1.geometry}
        material={gltf.materials["Material.005"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_2.geometry}
        material={gltf.materials.azul}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_3.geometry}
        material={gltf.materials["Material.002"]}
      />
    </T.Group>
    <T.Group
      position={[-247.77, 12.4, 0.25]}
      rotation={[Math.PI, -0.58, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle008_1.geometry}
        material={gltf.materials["Material.005"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_2.geometry}
        material={gltf.materials.azul}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_3.geometry}
        material={gltf.materials["Material.002"]}
      />
    </T.Group>
    <T.Group
      position={[221.92, 12.4, 139.55]}
      rotation={[Math.PI, -0.58, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle008_1.geometry}
        material={gltf.materials["Material.005"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_2.geometry}
        material={gltf.materials.azul}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_3.geometry}
        material={gltf.materials["Material.002"]}
      />
    </T.Group>
    <T.Group position={[-1.16, -0.05, -3.79]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[29.62, -0.05, -43.77]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[29.62, -0.05, 36.11]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[68.37, -0.05, -4.14]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[99.53, -0.05, -54]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[-202.16, -0.05, -174.13]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[-211.36, -0.05, -223.74]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[-151.91, -0.05, -170.39]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group position={[-155.98, -0.05, -226.1]} rotation={[0, 0.84, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group
      position={[229.37, -0.05, 227.46]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group
      position={[240.31, -0.05, 276.72]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group
      position={[179.02, -0.05, 225.49]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Group
      position={[185.05, -0.05, 281.02]}
      rotation={[Math.PI, -0.87, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Circle_1.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle_2.geometry}
        material={gltf.materials["Material.005"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Suelo_1.geometry}
      material={gltf.materials["Material.005"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Suelo_2.geometry}
      material={gltf.materials["Material.006"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Suelo_3.geometry}
      material={gltf.materials["Material.026"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Puente.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Puente_1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle003_1.geometry}
      material={gltf.materials["Material.008"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle003_2.geometry}
      material={gltf.materials["Material.009"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle004_1.geometry}
      material={gltf.materials["Material.008"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle004_2.geometry}
      material={gltf.materials["Material.009"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Escalera1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Escalera1_1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle005_1.geometry}
      material={gltf.materials["Material.008"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle005_2.geometry}
      material={gltf.materials["Material.009"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Escalera2.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Escalera2_1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle006_1.geometry}
      material={gltf.materials["Material.008"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle006_2.geometry}
      material={gltf.materials["Material.009"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle007_1.geometry}
      material={gltf.materials["Material.008"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle007_2.geometry}
      material={gltf.materials["Material.009"]}
    />
    <T.Mesh
      geometry={gltf.nodes.canon1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.canon1_1.geometry}
      material={gltf.materials["Material.023"]}
    />
    <T.Mesh
      geometry={gltf.nodes.canon2.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.canon2_1.geometry}
      material={gltf.materials["Material.023"]}
    />
    <T.Mesh
      geometry={gltf.nodes.canon3.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.canon3_1.geometry}
      material={gltf.materials["Material.023"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle002_1.geometry}
      material={gltf.materials["Material.008"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle002_2.geometry}
      material={gltf.materials["Material.009"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa2.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa2_1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa2_2.geometry}
      material={gltf.materials["Material.013"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa2_3.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa2_4.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa2_5.geometry}
      material={gltf.materials["Material.019"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa2_6.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa1_1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa1_2.geometry}
      material={gltf.materials["Material.013"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa1_3.geometry}
      material={gltf.materials["Material.018"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa1_4.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa1_5.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa1_6.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa4.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa4_1.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa4_2.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa4_3.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa4_4.geometry}
      material={gltf.materials["Material.022"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa4_5.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa4_6.geometry}
      material={gltf.materials["Material.013"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3_1.geometry}
      material={gltf.materials["Material.013"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3_2.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3_3.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3_4.geometry}
      material={gltf.materials["Material.014"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3_5.geometry}
      material={gltf.materials["Material.014"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3_6.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Casa3_7.geometry}
      material={gltf.materials["Material.021"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle001_1.geometry}
      material={gltf.materials["Material.005"]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle001_2.geometry}
      material={gltf.materials.azul}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle001_3.geometry}
      material={gltf.materials["Material.002"]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
