<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 .\islandCoin.glb -T --draco /draco/
-->

<script>
  import { T, useTask } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  let {
    coinInfo = {},
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/islandCoin-transformed.glb", {
    dracoLoader: useDraco(),
  });

  let time = 0;

  let refCoin = $state();

  useTask((delta) => {
    if (!refCoin) return;
    time += delta;

    const floatingHeight = Math.sin(time * 2) * 0.3;
    refCoin.position.y = 2 + floatingHeight;
    refCoin.rotation.y += 0.01;
  });
</script>

<T.Group
  bind:ref={refCoin}
  position={[coinInfo.position.x, 2, coinInfo.position.z]}
  dispose={false}
  scale={[0.5, 0.5, 0.5]}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cylinder001.geometry}
      material={gltf.materials["Material.001"]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve002.geometry}
      material={gltf.materials["Material.004"]}
      position={[-0.02, 0.31, 0.07]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={2.14}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve001.geometry}
      material={gltf.materials["Material.004"]}
      position={[-0.02, 0.31, -0.1]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={-2.14}
    />
    <T.Group
      position={[0.12, -0.14, 0.07]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={2.14}
    >
      <T.Mesh
        geometry={gltf.nodes.Curve004_1.geometry}
        material={gltf.materials.SVGMat}
      />
      <T.Mesh
        geometry={gltf.nodes.Curve004_2.geometry}
        material={gltf.materials["Material.002"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Curve004_3.geometry}
        material={gltf.materials["Material.004"]}
      />
    </T.Group>
    <T.Group
      position={[0.12, -0.14, -0.11]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={-2.14}
    >
      <T.Mesh
        geometry={gltf.nodes.Curve004_1.geometry}
        material={gltf.materials.SVGMat}
      />
      <T.Mesh
        geometry={gltf.nodes.Curve004_2.geometry}
        material={gltf.materials["Material.002"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Curve004_3.geometry}
        material={gltf.materials["Material.004"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Curve005.geometry}
      material={gltf.materials["Material.002"]}
      position={[0.12, -0.14, 0.07]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={2.14}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve006.geometry}
      material={gltf.materials["Material.002"]}
      position={[0.12, -0.14, -0.11]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={-2.14}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
