<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 .\boat.glb -T --draco /draco/
-->

<script lang="ts">
  import type { RigidBody as RapierRigidBody } from "@dimforge/rapier3d-compat";
  import { T, useTask, useThrelte } from "@threlte/core";
  import { useGltf, useDraco, Outlines, HTML } from "@threlte/extras";
  import { AutoColliders, RigidBody } from "@threlte/rapier";
  import { Group, Mesh, PerspectiveCamera, Vector3 } from "three";

  let {
    player,
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/boat-transformed.glb", { dracoLoader: useDraco() });

  let position: [number, number, number] = $state<[number, number, number]>([
    0, 0, 0,
  ]);

  let mainGroupRef: Group | undefined = $state<Group>();
  let objectRef: Group | undefined = $state<Group>();
  let rigidBody: RapierRigidBody | undefined = $state<RapierRigidBody>();

  useTask(() => {
    if (!rigidBody || !objectRef || !mainGroupRef) return;
    position = [player.position.x, player.position.y, player.position.z];

    rigidBody.setTranslation(
      { x: player.position.x, y: player.position.y, z: player.position.z },
      true
    );
    rigidBody.setRotation(
      {
        x: player.rotation.x,
        y: player.rotation.y,
        z: player.rotation.z,
        w: player.rotation.w,
      },
      true
    );
  });
</script>

<T.Group {position} bind:ref={mainGroupRef} dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <RigidBody bind:rigidBody>
      <T.Group bind:ref={objectRef}>
        <T.Mesh
          geometry={gltf.nodes.flag_obj.geometry}
          material={gltf.materials["Material.031"]}
        />
        <T.Mesh
          geometry={gltf.nodes.big_flag.geometry}
          material={gltf.materials["Material.034"]}
        />
        <T.Mesh
          geometry={gltf.nodes.flag.geometry}
          material={gltf.materials["Material.034"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube.geometry}
          material={gltf.materials["Material.030"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube001.geometry}
          material={gltf.materials["Material.031"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube002.geometry}
          material={gltf.materials["Material.034"]}
        />
        <AutoColliders shape="cuboid">
          <T.Mesh
            geometry={gltf.nodes.Plane003.geometry}
            material={gltf.materials["Material.029"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Plane003_1.geometry}
            material={gltf.materials["Material.030"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Plane003_2.geometry}
            material={gltf.materials["border oro.001"]}
          />
        </AutoColliders>
        <AutoColliders shape="cuboid">
          <T.Mesh
            geometry={gltf.nodes.Plane009.geometry}
            material={gltf.materials["Material.032"]}
          />
          <T.Mesh
            geometry={gltf.nodes.Plane009_1.geometry}
            material={gltf.materials["Material.033"]}
          />
        </AutoColliders>

        <T.Mesh
          geometry={gltf.nodes.Circle003.geometry}
          material={gltf.materials["Material.030"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Circle003_1.geometry}
          material={gltf.materials["Material.031"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Circle004.geometry}
          material={gltf.materials["Material.035"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Circle004_1.geometry}
          material={gltf.materials["Material.036"]}
        />
      </T.Group>
    </RigidBody>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
