<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 .\boat.glb -T --draco /draco/
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/boat-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.flag_obj.geometry}
      material={gltf.materials['Material.031']}
    />
    <T.Mesh
      geometry={gltf.nodes.big_flag.geometry}
      material={gltf.materials['Material.034']}
    />
    <T.Mesh
      geometry={gltf.nodes.flag.geometry}
      material={gltf.materials['Material.034']}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials['Material.030']}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials['Material.031']}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials['Material.034']}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane003.geometry}
      material={gltf.materials['Material.029']}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane003_1.geometry}
      material={gltf.materials['Material.030']}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane003_2.geometry}
      material={gltf.materials['border oro.001']}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane009.geometry}
      material={gltf.materials['Material.032']}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane009_1.geometry}
      material={gltf.materials['Material.033']}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle003.geometry}
      material={gltf.materials['Material.030']}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle003_1.geometry}
      material={gltf.materials['Material.031']}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle004.geometry}
      material={gltf.materials['Material.035']}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle004_1.geometry}
      material={gltf.materials['Material.036']}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
